### ISSUE TITLE
Not able to assign IPs

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder-bugs#29]
With the current release (v0.6.4) not able to assign any IPs that are not related to lambda function.
This is blocker issue and basic functionality.

Ability to assign any GW SDK IP should be always present.

**Comment by ggrig** [comment]
@MaNe2020 
Please add steps to replicate the issue

**Comment by MaNe2020** [comment]
@ggrig 
1. Navigate to setIPs and enter IP that is not one of the IPs you can load from AWS
2. Go to Workflow and clera, load and start processing data from specific folder

After step 1, IPs you entered are being assigned
After step 2, IPs that are assign are not used, rather the one that are loaded from AWS

**Comment by ggrig** [comment]
As discussed with @MaNe2020, this comes from the utilization of dynamic IPs in the version under test
The version in the develop branch has utilization of dynamic IPs optional (USE_DYNAMIC_ENDPOINTS option in .env) which by default is set to 'False'
The fix is available starting from the version labeled "v0.7.2"

**Comment by samarthdd** [comment]
@MaNe2020 I can confirm that this is fixed in develop branch

**Comment by kekesimarti** [comment]
@GINAGC I moved it to the 'For release' column.
